### ISSUE TITLE
在beamer及其它文档类使用中的问题

### ISSUE THREAD

**Issue by registor** [xiaoleeza/WeiChat#1]
我将你的绘制代码重新整理为qqchat.sty宏包（主要是删除了页面设置），以便在beamer等其它文档类中使用，我的思路是在minipage中进行绘制，但我不知道如何获得minipage的宽、高、各个参考点的坐标，于是，我将你的代码中的相差坐标改成了绝对坐标，但有两个主要问题，一是\time{}命令必须置于\SysTime{}或\myMessage{}之后，且必须使用\\换行后，后续排版才是正确的。二是\InputMessage{}命令只能放在聊天记录命令之前，否则位置会出错，并且与“article”文档类的位置无法一致，我暂时未能找到更好的办法来解决。

我Fork了一份你的代码，并进行了修改。希望能一起完成这个minipage的想法，谢谢。

**Comment by xiaoleeza** [comment]
minipage?你说的聊天气泡还是qq的整个界面？我看了下你的使用场景，其实可以先用我的方式编译出来qq界面，然后用插图的方式把对应的页面插入到article或者beamer里面更省力
```TeX
\usepackage{graphicx}

\includegraphics[page=2]{QQ.pdf}
\includegraphics[page=5]{QQ.pdf}
```

**Comment by registor** [comment]
谢谢你的回复，我是想将整个界面加入，你给出的方法也是我用过的方法，比较省力，但如果能做一个宏包，调整修改可能会更为方便一些。特别是beamer会自动使用无衬线字体，效果会更好一些。
